{
  "os": "linux",
  "jdk": [
    "oraclejdk8"
  ],
  "dist": "trusty",
  "group": "stable",
  "script": [
    "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=demos-parent -Dsonar.organization=devonmusa-github -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=3630727ab0814de69d76ea5012062476367a19d4"
  ],
  ".result": "configured",
  "install": "mvn install -DskipTests=true -Dmaven.javadoc.skip=true",
  "branches": {
    "only": [
      "master"
    ]
  },
  "language": "java",
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)"
  ]
}


