server:
  port: 8443
  http2:
    enable: true
#  ssl:
  #key-store: classpath: xxxx.p12
  # key-store-type = PKCS12
  # server.ssl.key-store.password = password
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql?serverTimezone=UTC&useSSL=false&useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.devon.framework.spring.boot.controller.*Entity


logging:
  level:
    stdout: DEBUG
  normal:
    sizeCap: 5MB
  error:
    sizeCap: 1MB